### ISSUE TITLE
error running this ??

### ISSUE THREAD

**Issue by wolfomat** [shagu/mtg-browser#3]
ls: cannot access 'input/*.dlens.bin': No such file or directory
Preparing Resources
 - Extracting DelverLens Database
 - Copying Card Backup Database
cp: missing destination file operand after 'cache/cards.sqlite'
Try 'cp --help' for more information.
make: *** [Makefile:9: update] Error 1

**Comment by wolfomat** [comment]
okay, after looking into the make file, i just extracted the stuff by hand.
now i am getting this error:

    const ipattern = `{${card.color}} ${card.name.replaceAll('/', '|')} {${card.types}} (%s)`
                                                  ^

TypeError: card.name.replaceAll is not a function
    at C:\dev\projects\mtg-browser-master\main.js:108:51
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\dev\projects\mtg-browser-master\main.js:68:7)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m
make: *** [Makefile:14: core] Error 1

**Comment by shagu** [comment]
Hi, please have a look at: https://github.com/shagu/mtg-browser/issues/2

I think you're running an old version of Node.js

**Comment by wolfomat** [comment]
take new node.js, now it hangs on a missing column "skryfall_id" in cards.
How can i get this id in delver?!
